on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - run: npm install
      - run: npm run changelog --silent > changelog.md
      - run: npm run build-release
          
      - uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
          files: web-ext-artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
